#+title: Emacs frontend to GNU Global source code tagging system
#+author: dalu
#+date: 2021:06:09

* Table of Contents                                               :TOC:noexport:
- [[#about][About]]
- [[#features][Features]]
- [[#config][Config]]
- [[#usage][Usage]]
  - [[#ggtags-find-tag-dwim][ggtags-find-tag-dwim]]
  - [[#ggtags-find-tag-mouse][ggtags-find-tag-mouse]]
  - [[#ggtags-find-definition][ggtags-find-definition]]
  - [[#ggtags-find-reference][ggtags-find-reference]]
  - [[#ggtags-find-other-symbol][ggtags-find-other-symbol]]
  - [[#ggtags-find-tag-regexp][ggtags-find-tag-regexp]]
  - [[#ggtags-idutils-query][ggtags-idutils-query]]
  - [[#ggtags-grep][ggtags-grep]]
  - [[#ggtags-find-file][ggtags-find-file]]
  - [[#ggtags-query-replace][ggtags-query-replace]]
- [[#handling-multiple-matches][Handling multiple matches]]
  - [[#m-n][~M-n~]]
  - [[#m-p][~M-p~]]
  - [[#m-][~M-}~]]
  - [[#m--1][~M-{~]]
  - [[#m--2][~M-=~]]
  - [[#m--3][~M-<~]]
  - [[#m--4][~M->~]]
  - [[#c-m-s-or-m-s-s][~C-M-s~ or ~M-s s~]]
  - [[#ret][~RET~]]
  - [[#m--m--if-emacs--25][~M-,~ (~M-*~ if Emacs < 25)]]
- [[#miscellaneous-commands][Miscellaneous commands]]
  - [[#ggtags-prev-mark][ggtags-prev-mark]]
  - [[#ggtags-next-mark][ggtags-next-mark]]
  - [[#ggtags-view-tag-history][ggtags-view-tag-history]]
  - [[#ggtags-view-search-history][ggtags-view-search-history]]
  - [[#ggtags-kill-file-buffers][ggtags-kill-file-buffers]]
  - [[#ggtags-toggle-project-read-only][ggtags-toggle-project-read-only]]
  - [[#ggtags-visit-project-root][ggtags-visit-project-root]]
  - [[#ggtags-delete-tags][ggtags-delete-tags]]
  - [[#ggtags-explain-tags][ggtags-explain-tags]]
  - [[#ggtags-browse-file-as-hypertext][ggtags-browse-file-as-hypertext]]

* About

  The package is aimed to make working with GNU Global in Emacs as
  effortlessly and intuitively as possible and to integrate tightly with
  standard emacs packages.

* Features

  - Build on ~compile.el~ for asynchronicity and its large feature-set.
  - Automatically update Global's tag files when needed with tuning for
    large source trees.
  - Intuitive navigation among multiple matches with mode-line display
    of current match, total matches and exit status.
  - Read tag with completion.
  - Show definition at point.
  - Jump to #include files.
  - Support search history and saving a search to register/bookmark.
  - Query replace.
  - Manage Global's environment variables on a per-project basis.
  - Highlight (definition) tag at point.
  - Abbreviated display of file names.
  - Support all Global search backends: ~grep~ ~idutils~ etc.
  - Support =exuberant/universal ctags= and ~pygments~ backend.
  - Support all Global's output formats: ~grep~ ~ctags-x~, ~cscope~, etc.
  - Support projects on remote hosts (e.g. via ~tramp~).
  - Support eldoc.
  - Search ~GTAGSLIBPATH~ for references and symbols.

* Config

  Global with ~universal-ctags~ and ~pygments~ plugins can support
  dozens of programming languages. For example, to enable ~ggtags-mode~
  for C/C++/Java modes::

  #+begin_src elisp
    (add-hook 'prog-mode-hook
              (lambda ()
                (when (derived-mode-p 'c-mode 'c++-mode 'java-mode)
                  (ggtags-mode 1))))
  #+end_src

* Usage

  Open any file in a project and type ~M-x ggtags-mode~. Use ~M-.~
  (~ggtags-find-tag-dwim~) to find the tag at point. If the project has
  not been indexed (i.e. no ~GTAGS~ file exists), ~ggtags~ will ask for
  the project root directory and index it recursively.  Alternatively
  one can invoke ~ggtags-create-tags~ to index a directory. The mode
  line will display the directory name next to the buffer name. If point
  is at a valid definition tag, it is underlined.

  ~ggtags~ is similar to the standard ~etags~ package. For example these
  keys ~M-.~, ~M-?~ and ~C-M-.~ should work as expected in
  ~ggtags-mode~.

  The following search commands are available:

** ggtags-find-tag-dwim

   Find a tag by context.

   If point is at a definition tag, find references, and vice versa.
   If point is at a line that matches ~ggtags-include-pattern~, find
   the include file instead.

   To force finding a definition tag, call it with a prefix (~C-u~).

** ggtags-find-tag-mouse

   Like ~ggtags-find-tag-dwim~ but suitable for binding to mouse
   events.

** ggtags-find-definition

   Find definition tags. With ~C-u~ ask for the tag name with
   completion.

** ggtags-find-reference

   Find reference tags. With ~C-u~ ask for the tag name with completion.

** ggtags-find-other-symbol

   Find tags that have no definitions. With ~C-u~ ask for the tag
   name with completion.

** ggtags-find-tag-regexp

   Find definition tags matching a regexp. By default it lists all
   matching tags in the project. With ~C-u~ restrict the lists to a
   directory of choice.

** ggtags-idutils-query

   Use idutils to find matches.

** ggtags-grep

   Grep for lines matching a regexp. This is usually the slowest.

** ggtags-find-file

   Find a file from all the files indexed by ~gtags~.

** ggtags-query-replace

   Do a query replace in all files found in a search.

* Handling multiple matches

  When a search finds multiple matches, a buffer named
  ~*ggtags-global*~ is popped up and ~ggtags-navigation-mode~ is
  turned on to facilitate locating the right match.
  ~ggtags-navigation-mode~ makes a few commands in the
  ~*ggtags-global*~ buffer globally accessible:

** ~M-n~

   Move to the next match.

** ~M-p~

   Move to the previous match.

** ~M-}~

   Move to next file.

** ~M-{~

   Move to previous file.

** ~M-=~

   Move to the file where navigation session starts.

** ~M-<~

   Move to the first match.

** ~M->~

   Move to the last match.

** ~C-M-s~ or ~M-s s~

   Use ~isearch~ to find the match.

** ~RET~

   Found the right match so exit navigation mode. Resumable by
   ~M-x tags-loop-continue~.

** ~M-,~ (~M-*~ if Emacs < 25)

   Abort and go back to the location where the search was started.

* Miscellaneous commands

  Commands are available from the ~Ggtags~ menu in ~ggtags-mode~.

** ggtags-prev-mark

   Move to the previously (older) visited location. Unlike ~M-,~
   (~M-*~ if Emacs < 25) this doesn't delete the location from the
   tag ring.

** ggtags-next-mark

   Move to the next (newer) visited location.

** ggtags-view-tag-history

   Pop to a buffer listing all visited locations from newest to
   oldest. The buffer is a next error buffer and works with standard
   commands ~next-error~ and ~previous-error~. In addition ~TAB~
   and ~S-TAB~ move to next/prev entry, and ~RET~ visits the
   location. ~M-n~ and ~M-p~ move to and display the next/previous
   entry.

** ggtags-view-search-history

   View or re-run past searches as kept in
   ~ggtags-global-search-history~.

** ggtags-kill-file-buffers

   Kill all file-visiting buffers of current project.

** ggtags-toggle-project-read-only

   Toggle opening files in ~read-only~ mode. Handy if the main
   purpose of source navigation is to read code.

** ggtags-visit-project-root

   Open the project root directory in ~dired~.

** ggtags-delete-tags

   Delete the GTAGS, GRTAGS, GPATH and ID files of current project.

** ggtags-explain-tags

   Explain how each file is indexed in current project.

** ggtags-browse-file-as-hypertext

   Use ~htags~ to generate HTML of the source tree. This allows
   browsing the project in a browser with cross-references.
